development:
  adapter: postgre
  database: mydb_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgre
  database: mydb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgre
  database: mydb_prod
  pool: 5
  timeout: 5000