development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

test:
  adapter: postgresql
  database: mydb_test
  pool: 5
  timeout: 5000
  username: postgres
  password: root

production:
  adapter: postgresql
  database: mydb_prod
  pool: 5
  timeout: 5000
  username: postgres
  password: root